### ISSUE TITLE
Peer peer code review

### ISSUE THREAD

**Issue by Chandan-devs-tech** [rubydevi/meal-capstone#27]
Hi @rubydevi,
- Great job is done so far some required changes

# Required Changes ♻️ 

- Please try to use the ES6 Module `Arrow function`  in place of the normal function It's best to practice javaScript ES6.
<img width="401" alt="ruby" src="https://github.com/rubydevi/meal-capstone/assets/65088027/70da7226-ce5d-490d-8327-2c5289f3dcc5">

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

**Comment by rubydevi** [comment]
@Chandan-devs-tech thanks for your review, I have resolved this issue.
